spring:
#    Configuration GRAPHQL
  graphql:
    schema:
      locations: classpath:graphql/*.graphqls
    path: /graphql
#    Configuration GRAPHIQL
    graphiql:
      enabled: true
      path: /graphiql
